### ISSUE TITLE
请问是哪种蒸馏方案呢？

### ISSUE THREAD

**Issue by nlp4whp** [CLUEbenchmark/DistilBert#1]
首先感谢作者一系列关于中文bert的开源贡献

想问下，这里是复刻huggingface的蒸馏方案，还是类似tinyBERT那种计算多层loss呢？

**Comment by brightmart** [comment]
优先，huggingface的蒸馏方案；
tinyBERT听说一周左右就会开源。
我们也会全面的比较这几个模型在CLUE benchmark任务上的效果。

**Comment by nlp4whp** [comment]
> 优先，huggingface的蒸馏方案；
> tinyBERT听说一周左右就会开源。
> 我们也会全面的比较这几个模型在CLUE benchmark任务上的效果。

期待~
BTW. tinyBERT终于要开源了
